apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "argo-workflow-creator"
rules:
  - apiGroups:
      - argoproj.io
    resources:
      - workflows
    verbs:
      - get
      - create
      - patch
---
{{- range $_, $value := index .Values "argo-workflows" "controller" "workflowNamespaces" }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: "argo-workflow-creator"
  namespace: {{ $value | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "argo-workflow-creator"
subjects:
  - kind: ServiceAccount
    name: "argo-workflow"
    namespace: {{ $value | quote }}
{{- end }}
