apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: pong
spec:
  template:
    serviceAccountName: operate-workflow-sa
  dependencies:
    - name: test-dep
      eventSourceName: ping
      eventName: ping
  triggers:
    - template:
        name: pong-workflow-trigger
        k8s:
          operation: create
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: pong-
              spec:
                workflowTemplateRef:
                  name: argo-echo
                arguments:
                  parameters:
                    - name: message
                      value: ""
          parameters:
            - src:
                dependencyName: test-dep
                dataKey: body.message
              dest: spec.arguments.parameters.0.value
